
random.streets <- c(
    "Catherine Street",
    "Willow Street",
    "Prospect Avenue",
    "Oak Lane",
    "Hickory Street",
    "School Street",
    "Main Street North",
    "Old York Road",
    "Berkshire Drive",
    "Smith Street",
    "Cobblestone Court",
    "5th Street",
    "Oak Avenue",
    "Mill Street",
    "Spruce Avenue",
    "Route 202",
    "Homestead Drive",
    "Howard Street",
    "Main Street West",
    "Mulberry Street",
    "Marshall Street",
    "Aspen Drive",
    "Oxford Road",
    "7th Street",
    "York Road",
    "Jackson Avenue",
    "Highland Drive",
    "Hanover Court",
    "Race Street",
    "Hilltop Road",
    "Valley View Drive",
    "Deerfield Drive",
    "Main Street",
    "Arlington Avenue",
    "Ivy Court",
    "Roberts Road",
    "Street Road",
    "2nd Street",
    "Briarwood Drive",
    "Lawrence Street",
    "Depot Street",
    "Church Street",
    "East Avenue",
    "Hartford Road",
    "Virginia Avenue",
    "Grant Avenue",
    "4th Street West",
    "Briarwood Court",
    "Fulton Street",
    "Railroad Avenue",
    "Lafayette Avenue",
    "Creekside Drive",
    "Lincoln Avenue",
    "Warren Street",
    "Maple Lane",
    "Manor Drive",
    "14th Street",
    "Elm Street",
    "Myrtle Street",
    "John Street",
    "6th Street",
    "Primrose Lane",
    "Cambridge Road",
    "Main Street South",
    "Cedar Lane",
    "Mulberry Court",
    "Tanglewood Drive",
    "Route 30",
    "Pleasant Street",
    "1st Avenue",
    "Route 5",
    "Bridle Lane",
    "Sycamore Street",
    "10th Street",
    "Forest Drive",
    "Washington Street",
    "5th Street West",
    "Route 6",
    "Walnut Avenue",
    "Riverside Drive",
    "Dogwood Drive",
    "Aspen Court",
    "Laurel Street",
    "Laurel Lane",
    "Pine Street",
    "Fairview Road",
    "Pheasant Run",
    "2nd Street East",
    "4th Street",
    "Mechanic Street",
    "2nd Street North",
    "Cambridge Drive",
    "Country Club Drive",
    "New Street",
    "Lake Avenue",
    "Railroad Street",
    "Andover Court",
    "Locust Street",
    "Delaware Avenue",
    "Edgewood Drive")


FakeAddress <- function(n){
    streets <- sample(random.streets, n, replace = FALSE)
    numbers <- sample(1:200, n, replace = TRUE)
    mapply(paste, numbers, streets)
}
